version: "2"
services:
  app:
    build: ./pyapp
    image: pythonapp:dockerdhub/pythonapp
    ports:
      - "5001:5000"
    restart: always  
  db:
    build: ./sql
    image: sqlapp:dockerdhub/pythonapp
    ports:
      - "3308:3306"
    env_file:
      - production.env
    restart: always  
