version: "2"
services:
  app:
    build: .
    ports:
      - "5001:5000"
  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    env_file:
      - production.env
    volumes:
      - ./sql-script/:/docker-entrypoint-initdb.d/